### ISSUE TITLE
Game client konstruktor

### ISSUE THREAD

**Issue by IevgenRagulin** [NoxArt/CityNameAnimal#6]
Druhým parametrem konstruktoru GameClient je jméno uživatele. Odkud ho vezmeme? Musí ho uživatel zadat když vytvoří hru, připojí se ke hře? Nebo vezmeme to s kontaktu? Nebo vygenerujeme automaticky?

**Comment by NoxArt** [comment]
Normálně bych to dal do globálního nastavení, ale může být problém, kdyby se sešli dva se stejným jménem, to zatim nevim jak nejlíp řešit

**Comment by IevgenRagulin** [comment]
Tak zatím to dám do vytvoření nové hry. Stejně ale se může stát že sejdou se dva se stejným jménem

**Comment by IevgenRagulin** [comment]
Nemůžu vytvořit objekt hry. Mohl bys mi prosím napsat co dělám špatně? Padá to na řádku createGame

```
String[] categories = new String[1];
categories[0] = "Město";
GameProperties gameProps = new GameProperties("cz",
                            "jmenohry", 5, null, 100,
                            4, "auto", categories);
GameClient gameClient = new GameClient("http://fit.noxart.cz/tam/", "Honza");
gameClient.createGame(gameProps);
```

```
11-16 09:58:48.918: E/AndroidRuntime(2639): FATAL EXCEPTION: main
11-16 09:58:48.918: E/AndroidRuntime(2639): java.lang.ClassCastException: libcore.net.http.HttpURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
11-16 09:58:48.918: E/AndroidRuntime(2639):     at cz.fit.tam.utils.HttpConnect.post(HttpConnect.java:58)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at cz.fit.tam.model.MessageQueue.sendMessage(MessageQueue.java:66)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at cz.fit.tam.model.GameClient.createGame(GameClient.java:64)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at cz.fit.tam.NewGameActivity$1.onClick(NewGameActivity.java:117)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at android.view.View.performClick(View.java:4240)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at android.view.View$PerformClick.run(View.java:17721)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at android.os.Handler.handleCallback(Handler.java:730)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at android.os.Handler.dispatchMessage(Handler.java:92)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at android.os.Looper.loop(Looper.java:137)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at android.app.ActivityThread.main(ActivityThread.java:5103)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at java.lang.reflect.Method.invokeNative(Native Method)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at java.lang.reflect.Method.invoke(Method.java:525)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
11-16 09:58:48.918: E/AndroidRuntime(2639):     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by NoxArt** [comment]
Promiň, dal jsem adresu serveru nepřesně: http<b>S</b>://fit.noxart.cz/tam/

**Comment by IevgenRagulin** [comment]
Díky
