### ISSUE TITLE
Problém v Game.stop()

### ISSUE THREAD

**Issue by IevgenRagulin** [NoxArt/CityNameAnimal#8]
Když zavolám metodu Game.stop() dostavám odpověd' od servera 'Missing argument: id'

Zkusil jsem zaměnit v Game.stop() game_id na id. Dostavám chybu 

```
11-17 18:34:56.943: E/MessageQueue(3305): null
11-17 18:34:56.943: E/MessageQueue(3305): org.json.JSONException: End of input at character 0 of 
11-17 18:34:56.943: E/MessageQueue(3305):   at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
11-17 18:34:56.943: E/MessageQueue(3305):   at org.json.JSONTokener.nextValue(JSONTokener.java:97)
11-17 18:34:56.943: E/MessageQueue(3305):   at org.json.JSONObject.<init>(JSONObject.java:154)
11-17 18:34:56.943: E/MessageQueue(3305):   at org.json.JSONObject.<init>(JSONObject.java:171)
11-17 18:34:56.943: E/MessageQueue(3305):   at cz.fit.tam.model.MessageQueue.sendMessage(MessageQueue.java:75)
11-17 18:34:56.943: E/MessageQueue(3305):   at cz.fit.tam.model.GameClient.stop(GameClient.java:147)
11-17 18:34:56.943: E/MessageQueue(3305):   at cz.fit.tam.model.Game.stop(Game.java:112)
11-17 18:34:56.943: E/MessageQueue(3305):   at cz.fit.tam.WaitForGameActivity$StopGameAsyncTask.doInBackground(WaitForGameActivity.java:99)
11-17 18:34:56.943: E/MessageQueue(3305):   at cz.fit.tam.WaitForGameActivity$StopGameAsyncTask.doInBackground(WaitForGameActivity.java:1)
11-17 18:34:56.943: E/MessageQueue(3305):   at android.os.AsyncTask$2.call(AsyncTask.java:287)
11-17 18:34:56.943: E/MessageQueue(3305):   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
11-17 18:34:56.943: E/MessageQueue(3305):   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
11-17 18:34:56.943: E/MessageQueue(3305):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
11-17 18:34:56.943: E/MessageQueue(3305):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
11-17 18:34:56.943: E/MessageQueue(3305):   at java.lang.Thread.run(Thread.java:841)
11-17 18:34:56.943: W/dalvikvm(3305): threadid=11: thread exiting with uncaught exception (group=0xb3f77648)
11-17 18:34:56.953: E/AndroidRuntime(3305): FATAL EXCEPTION: AsyncTask #1
11-17 18:34:56.953: E/AndroidRuntime(3305): java.lang.RuntimeException: An error occured while executing doInBackground()
11-17 18:34:56.953: E/AndroidRuntime(3305):     at android.os.AsyncTask$3.done(AsyncTask.java:299)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at java.util.concurrent.FutureTask.run(FutureTask.java:239)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at java.lang.Thread.run(Thread.java:841)
11-17 18:34:56.953: E/AndroidRuntime(3305): Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
11-17 18:34:56.953: E/AndroidRuntime(3305):     at android.os.Handler.<init>(Handler.java:197)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at android.os.Handler.<init>(Handler.java:111)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at android.widget.Toast$TN.<init>(Toast.java:324)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at android.widget.Toast.<init>(Toast.java:91)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at android.widget.Toast.makeText(Toast.java:238)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at cz.fit.tam.WaitForGameActivity$StopGameAsyncTask.doInBackground(WaitForGameActivity.java:101)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at cz.fit.tam.WaitForGameActivity$StopGameAsyncTask.doInBackground(WaitForGameActivity.java:1)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at android.os.AsyncTask$2.call(AsyncTask.java:287)
11-17 18:34:56.953: E/AndroidRuntime(3305):     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
11-17 18:34:56.953: E/AndroidRuntime(3305):     ... 4 more
```

**Comment by NoxArt** [comment]
Bylo to trochu níž, commitnul jsem, zkus teď
